name = "LoggingExtrasCompose"
uuid = "d5cfad3a-df3b-4959-ad72-66746aa58a7d"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
license = "MIT"
desc = "Enable LoggingExtras for LogCompose"
version = "0.1.1"

[deps]
LogCompose = "8416b438-731e-11ea-2421-05f642269042"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"

[compat]
julia = "1"
LoggingExtras = "0.4, 1"
LogCompose = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
